version: "3"

services:

  backend:
    build: .
    container_name: opsguardian_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

  monitor:
    build: .
    container_name: opsguardian_monitor
    command: python monitor.py
    depends_on:
      - backend
    restart: always